import React, { FC } from 'react'
import styles from '../layouts/Home.module.css'
import Head from 'next/head'
import Navbar from '../Navbar';

type ComponenteProps = {
  children: React.ReactNode
}

const MainLayout: FC <ComponenteProps> = ({children}) => {

    return (
        <div className={styles.container}>
          <Head>
            <title>Home Init</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <Navbar/>

          <main className={styles.main}>
            {children}
          </main>
        </div>
      );
}

export default MainLayout